trigger:
- master

variables:
  azureServiceConnection: AzureServiceConnection
  buildConfiguration: Release
  apiAppName: lab11api012345
  downloaderAppName: lab11downloader012345

stages:
- stage: BuildApi
  displayName: API - Build & Deploy
  jobs:
  - job: BuildApi
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: Publish API
      inputs:
        command: publish
        publishWebProjects: false
        projects: code/Api/Api.csproj
        arguments: >-
          -c $(buildConfiguration)
          -o $(Pipeline.Workspace)/api
     
    - publish: $(Pipeline.Workspace)/api
      artifact: artifact-api

- stage: DeployApi
  displayName: Deploy API Function
  dependsOn: BuildApi
  jobs:
  - job: DeployApi
    pool:
      vmImage: windows-latest
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download api artifact
        inputs:
          buildType: current
          artifact: artifact-api
          path: $(Pipeline.Workspace)/api
      - task: AzureFunctionApp@2
        inputs:
          AzureSubscription: $(azureServiceConnection)
          appType: functionApp
          appName: $(apiAppName)
          package: $(Pipeline.Workspace)/api/**/*.zip

- stage: BuildDownloader
  displayName: Downloader - Build & Deploy
  jobs:
  - job: BuildDownloader
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: Publish Downloader
      inputs:
        command: publish
        publishWebProjects: false
        projects: code/Downloader/Downloader.csproj
        arguments: >-
          -c $(buildConfiguration)
          -o $(Pipeline.Workspace)/downloader
     
    - publish: $(Pipeline.Workspace)/downloader
      artifact: artifact-downloader

- stage: DeployDownloader
  displayName: Deploy Downloader Function
  dependsOn: BuildDownloader
  jobs:
  - job: DeployDownloader
    pool:
      vmImage: windows-latest
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download downloader artifact
        inputs:
          buildType: current
          artifact: artifact-downloader
          path: $(Pipeline.Workspace)/downloader
      - task: AzureFunctionApp@2
        inputs:
          AzureSubscription: $(azureServiceConnection)
          appType: functionApp
          appName: $(downloaderAppName)
          package: $(Pipeline.Workspace)/downloader/**/*.zip