trigger: none

pr:
- master

stages:
- stage: VerifyCode
  displayName: Code verification
  jobs:

  - job: SonarAnalysis
    displayName: Sonar analysis
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - task: SonarCloudPrepare@4
      inputs:
        SonarQube: 'SonarQubeConnection'
        organization: 'vyagi-1'
        scannerMode: 'dotnet'
        projectKey: 'vyagi_PicturesDownloader'

    - script: dotnet build code/PicturesDownloader.sln --configuration Release
      displayName: Build solution

    - script: dotnet test code/PicturesDownloader.sln --configuration Release
      displayName: Test solution

    - task: SonarCloudAnalyze@4
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarCloudPublish@4
      inputs:
        pollingTimeoutSec: '300'

  - job: Api
    displayName: Api build & verify
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - script: dotnet build code/Api --configuration Release
      displayName: Build Api

    - script: dotnet test code/ApiTests --configuration Release
      displayName: Test Api

  - job: Downloader
    displayName: Downloader build & verify
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

        
    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - script: dotnet build code/Downloader --configuration Release
      displayName: Build Downloader

- stage: TerraformValidate
  displayName: Terraform validation
  dependsOn: VerifyCode
  jobs:

  - job: Terraform
    displayName: Terraform validate
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.6.6'
    - script: |
        cd terraform
        terraform init -backend=false
        terraform validate
      displayName: Terraform init & validate
