trigger:
- master

stages:
- stage: VerifyCode
  displayName: Code verification
  jobs:

  - job: Api
    displayName: Api build & verify
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - script: dotnet build code/Api --configuration Release
      displayName: Build Api

    - script: dotnet test code/ApiTests --configuration Release
      displayName: Test Api

  - job: Downloader
    displayName: Downloader build & verify
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - script: dotnet build code/Downloader --configuration Release
      displayName: Build Downloader

- stage: TerraformValidate
  displayName: Terraform validation
  dependsOn: VerifyCode
  jobs:

  - job: Terraform
    displayName: Terraform validate
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - script: |
        cd terraform
        terraform init -backend=false
        terraform validate
      displayName: Terraform init & validate