trigger:
- master

stages:
- stage: VerifyCode
  displayName: Code verification
  jobs:

  - job: Build
    displayName: Build Azure Functions
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.x'

    - script: dotnet build Api --configuration Release
      displayName: Build Api function

    - script: dotnet build Downloader --configuration Release
      displayName: Build Downloader function